name: Build Wheel

on: workflow_dispatch

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          python3 -m pip install wheel
      - name: build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_ARCHS: "auto64"
          CIBW_BUILD: cp36-*
          CIBW_SKIP: cp36-musllinux*
      - name: ls wheels
        run: |
          ls wheelhouse
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheelhouse
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Nightly Release'
          prerelease: true
          body: 'Nightly build'
          files: |
            ./wheelhouse/*.whl
